services:
  ippbx:
    image: ${IMAGE_NAME:-ippbx}:${IMAGE_TAG:-latest}
    container_name: ippbx
    ports:
      - "3003:3000"
    networks:
      - webapp
    env_file:
      - .env
networks:
  webapp:
    external: true
