export type Cdr = {
  uuid: string;
  start_stamp: string;
  ring_stamp?: string;
  answer_stamp?: string;
  end_stamp: string;
  duration: string;
  billsec: string;
  billsec_min: string;
  hangup_cause: string;
  direction: "inbound" | "outbound" | "internal";
  account_code: string;
  caller_id_number: string;
  caller_id_name: string;
  destination_number: string;
  context: string;
  bleg_uuid?: string;
  other_uuid?: string;
  sip_call_id: string;
  sip_hangup_disposition?: string;
  sip_invite_failure_status: string;
  xui_route_ids: string;
  xui_hangup_cause?: string;
  external_tracking_id: string;
  hostname: string;
  network_addr: string;
  network_port: string;
  caller_source: string;
  rtp_use_codec_name: string;
  video_read_codec: string;
  video_write_codec: string;
  video_media_flow: string;
  rel_path: string;
  abs_path: string;
  media_file_id: string;
  digits_dialed: string;
  realm: string;
};
